# Generated by Django 5.2 on 2025-06-16 20:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('rape', 'Rape'), ('assault', 'Assault'), ('domestic_violence', 'Domestic Violence'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_encrypted', models.TextField(blank=True, null=True)),
                ('voice_note_url', models.URLField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user'], name='reports_inc_user_id_fd1f44_idx'), models.Index(fields=['type'], name='reports_inc_type_510025_idx'), models.Index(fields=['status'], name='reports_inc_status_24c31e_idx'), models.Index(fields=['submitted_at'], name='reports_inc_submitt_a2b3ba_idx')],
            },
        ),
    ]
