# Generated by Django 5.2 on 2025-06-16 20:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('type', models.CharField(choices=[('police', 'Police Station'), ('hospital', 'Hospital/Health Center'), ('ngo', 'NGO/Support Organization'), ('government', 'Government Office'), ('shelter', 'Shelter'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.CharField(max_length=100)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('woreda', models.CharField(blank=True, max_length=100, null=True)),
                ('kebele', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('alt_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('hours_of_operation', models.TextField(blank=True, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['type'], name='agencies_ag_type_f0a138_idx'), models.Index(fields=['region'], name='agencies_ag_region_ba0a6a_idx'), models.Index(fields=['zone'], name='agencies_ag_zone_cf2b5b_idx'), models.Index(fields=['active'], name='agencies_ag_active_d638c4_idx')],
            },
        ),
    ]
