/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/hdmsofob/gettext"
#define EXEC_PREFIX "/home/hdmsofob/gettext"
#define BINDIR "/home/hdmsofob/gettext/bin"
#define SBINDIR "/home/hdmsofob/gettext/sbin"
#define LIBEXECDIR "/home/hdmsofob/gettext/libexec"
#define DATAROOTDIR "/home/hdmsofob/gettext/share"
#define DATADIR "/home/hdmsofob/gettext/share"
#define SYSCONFDIR "/home/hdmsofob/gettext/etc"
#define SHAREDSTATEDIR "/home/hdmsofob/gettext/com"
#define LOCALSTATEDIR "/home/hdmsofob/gettext/var"
#define RUNSTATEDIR "/home/hdmsofob/gettext/var/run"
#define INCLUDEDIR "/home/hdmsofob/gettext/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/hdmsofob/gettext/share/doc/gettext"
#define INFODIR "/home/hdmsofob/gettext/share/info"
#define HTMLDIR "/home/hdmsofob/gettext/share/doc/gettext"
#define DVIDIR "/home/hdmsofob/gettext/share/doc/gettext"
#define PDFDIR "/home/hdmsofob/gettext/share/doc/gettext"
#define PSDIR "/home/hdmsofob/gettext/share/doc/gettext"
#define LIBDIR "/home/hdmsofob/gettext/lib"
#define LISPDIR "/home/hdmsofob/gettext/share/emacs/site-lisp"
#define LOCALEDIR "/home/hdmsofob/gettext/share/locale"
#define MANDIR "/home/hdmsofob/gettext/share/man"
#define PKGDATADIR "/home/hdmsofob/gettext/share/gettext"
#define PKGINCLUDEDIR "/home/hdmsofob/gettext/include/gettext-tools"
#define PKGLIBDIR "/home/hdmsofob/gettext/lib/gettext-tools"
#define PKGLIBEXECDIR "/home/hdmsofob/gettext/libexec/gettext-tools"
